name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
          
    - name: Build and push browser extension
      uses: docker/build-push-action@v6
      with:
        context: ./browser-extension
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/browser-extension:${{ steps.meta.outputs.version }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Build and push backend service
      uses: docker/build-push-action@v6
      with:
        context: ./backend-verification-service
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend-service:${{ steps.meta.outputs.version }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Build and push data pipeline
      uses: docker/build-push-action@v6
      with:
        context: ./data-pipeline
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/data-pipeline:${{ steps.meta.outputs.version }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          ## What's Changed
          
          This release includes:
          - Browser extension updates
          - Backend service improvements
          - Data pipeline enhancements
          
          ## Docker Images
          
          - Browser Extension: `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/browser-extension:${{ steps.meta.outputs.version }}`
          - Backend Service: `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend-service:${{ steps.meta.outputs.version }}`
          - Data Pipeline: `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/data-pipeline:${{ steps.meta.outputs.version }}`
          
          ## Installation
          
          See the [documentation](https://github.com/${{ github.repository }}/blob/main/README.md) for installation instructions. 